#!/bin/bash

SETTINGS_FILE=~/.git-iam
WRITE=1

GLOBAL=$(git config --global user.email)


function read_settings {
    GREP=$(grep "\(.*\)=$1" -- $SETTINGS_FILE)
    USERNAME=$(echo $GREP | sed -e "s/=$1//g")
    echo $USERNAME
}


if [[ -z "$1" ]]; then
    # no arguments. who am i on the repo? local > global (read)
    EMAIL=$(git config user.email)
    WRITE=0
elif [[ $1 == *@* ]]; then
    # write with an email address
    EMAIL=$1
else
    # write with settings file
    if [[ -e $SETTINGS_FILE ]]; then
        GREP=$(grep "^$1=\(.*\)$" -- $SETTINGS_FILE)
        if [[ -z $GREP ]]; then
            echo "$1 is not setup in $SETTINGS_FILE"
            exit 1
        else
            EMAIL=$(echo $GREP | sed -e "s/^$1=//g")
        fi
    else
        echo "$SETTINGS_FILE doesn't exist."
        exit 1
    fi
fi

USERNAME=$(read_settings $EMAIL)
echo "This repository is now using: $EMAIL ($USERNAME)"

# do the actual write on git
if [[ $WRITE = 1 ]]; then
    if [[ "$GLOBAL" = "$EMAIL" ]]; then
        git config --local --unset user.email
    else
        git config --local user.email $EMAIL
    fi
fi
