#!/bin/bash

NEXT=$1
MESSAGE=$2

if [[ -z "$MESSAGE" ]]; then
    MESSAGE=$(git log -n 1 --no-merges --pretty=%s)
fi

if [[ $# < 1 ]]; then
    echo -e "usage: git release increment:patch|minor|major|x.x.x [message]"
    exit 1
fi

if [[ -z "$VERSION" ]]; then
    VERSION=$(git tag -l | grep "^v[0-9]\.[0-9]\.[0-9]" | sort | tail -n 1 | tr -d "v")
fi

NEXT_VERSION=v$(bump $NEXT $VERSION)
if [[ $? != 0 ]]; then
    echo "Unable to define new version. Make sure you define your version in the command or if it's defined through your tags."
    exit 1
fi

git tag -a $NEXT_VERSION -m "$MESSAGE"
