#!/bin/bash

if [[ $# = 0 ]]; then
    echo "usage: git iam <nickname>"
    exit 1
fi

SETTINGS_FILE=~/.git-iam
if [[ -e $SETTINGS_FILE ]]; then
    if [[ $1 == *@* ]]; then
        EMAIL=$1
    else
        GREP=$(grep "^$1=\(.*\)$" -- $SETTINGS_FILE)
        if [[ -z $GREP ]]; then
            echo "$1 is not setup in $SETTINGS_FILE"
            exit 1
        else
            EMAIL=$(echo $GREP | sed -e "s/^$1=//g")
        fi
    fi
    echo "This repository is now using: $EMAIL"
    git config user.email $EMAIL
else
    echo "$SETTINGS_FILE doesn't exist."
    exit 1
fi

