#!/bin/bash

NEXT=$1
MESSAGE=$2

if [[ -z "$MESSAGE" ]]; then
    MESSAGE=$(git log -n 1 --no-merges --pretty=%s)
fi

if [[ $# < 1 ]]; then
    echo -e "usage: git release increment:patch|minor|major|x.x.x [message]"
    exit 1
fi

VERSION=$(git describe --abbrev=0 --tags --match="v*" | tr -d "v")

NEXT_VERSION=v$(bump $NEXT $VERSION)
if [[ $? != 0 ]]; then
    echo "Unable to define new version. Make sure you define your version in the command or if it's defined through your tags."
    exit 1
fi

git tag -a $NEXT_VERSION -m "$MESSAGE"
if [[ $? != 0 ]]; then
    echo "couldn't tag"
    exit 1
fi

echo $NEXT_VERSION

GITROOT="$(git rev-parse --show-toplevel)"
GIT_HOOK_POST_RELEASE=$GITROOT/.git/hooks/post-release

if [ -f "$GIT_HOOK_POST_RELEASE" ]; then
    $GIT_HOOK_POST_RELEASE $NEXT_VERSION
fi
