#!/bin/bash

SETTINGS_FILE=~/.git-iam
WRITE=1

GLOBAL=$(git config --global --get user.email)


if [[ -z "$1" ]]; then
    EMAIL=$(git config --local --get user.email)
    WRITE=0
elif [[ $1 == *@* ]]; then
    EMAIL=$1
else
    if [[ -e $SETTINGS_FILE ]]; then
        GREP=$(grep "^$1=\(.*\)$" -- $SETTINGS_FILE)
        if [[ -z $GREP ]]; then
            echo "$1 is not setup in $SETTINGS_FILE"
            exit 1
        else
            EMAIL=$(echo $GREP | sed -e "s/^$1=//g")
        fi
    else
        echo "$SETTINGS_FILE doesn't exist."
        exit 1
    fi
fi
echo "This repository is now using: $EMAIL"

if [[ $WRITE = 1 ]]; then
    if [[ "$GLOBAL" = "$EMAIL" ]]; then
        git config --local --unset user.email
    else
        git config --local user.email $EMAIL
    fi
fi
