#!/bin/bash

# usage: git ico [-r|--remote] [expression]

REMOTE=0

while [[ $# > 0 ]]; do
    key="$1"

    case $key in
        -r|--remote)
            REMOTE=1
            ;;
        *)
            EXPR=$1
            ;;
    esac
    shift
done


if [[ $REMOTE = 1 ]]; then
    BRANCHES=$(git branch -r | cut -d " " -f 2,3)
else
    BRANCHES=$(git branch | cut -d " " -f 2,3)
fi

if [[ -n "$EXPR" ]]; then
    BRANCHES=$(echo $BRANCHES | grep $EXPR)
fi


N=0
for i in $BRANCHES ; do
      BRANCHES[$N]="$i"
      echo "$N = $i"
  let "N= $N + 1"
done

echo -n "Checkout to branch #: "
read choice

git checkout ${BRANCHES[$choice]}
