#!/bin/bash

GIT_ROOT=$(git root)
NAME=$(git name | cut -d "/" -f 2)

NEXT_VERSION="$1"
if [[ -z "$NEXT_VERSION" ]]; then
    echo "not creating formula without specific version"
    exit 1
fi

HOMEBREW_TAP="$HOME/Code/homebrew-tap"

cd $GIT_ROOT && git brew "$1" > $HOMEBREW_TAP/$NAME.rb

cd $HOMEBREW_TAP && git add -A && git commit -m "Bump $NAME to $NEXT_VERSION" && git push
